### ISSUE TITLE
Discourse Babble website link is dead

### ISSUE THREAD

**Issue by haykam821** [DeclanHoare/matterbabble#1]
It seems that the `Discourse Babble` link that is in the README that leads to https://discourse-babble.com/ is dead.

**Comment by DeclanHoare** [comment]
That's a shame - says the domain has expired.  I'll give it a little while to see if it gets renewed and if not I will update it to point to the GH repo instead.  Thanks for letting me know.

**Comment by haykam821** [comment]
Looks like the site is back up.
